CREATE TABLE SUP(SUPPLIER_CODE VARCHAR(5), SUPPLIER_NAME VARCHAR(20), SUPPLIER_CITY VARCHAR(10), TURNOVER INTEGER);
CREATE TABLE PA(PART_CODE INTEGER, WEIGHT DOUBLE, COLOR VARCHAR(10), COST INTEGER , SELLING_PRICE DOUBLE);
CREATE TABLE SUPPART(SUPPLIER_CODE VARCHAR(5), PART_CODE INTEGER, QUANTITY INTEGER);
INSERT INTO SUP(SUPPLIER_CODE,SUPPLIER_NAME,SUPPLIER_CITY,TURNOVER) VALUES ('S1000','RAMESH','LUCKNOW',120),('S1001','SALMAN','DELHI',NULL),('S1003','RAJEEV','BOMBAY',170),('S1004','NEERAJ','BOMBAY',110),('S1005','MUKESH','HARYANA',78);
INSERT INTO PA(PART_CODE,WEIGHT,COLOR,COST,SELLING_PRICE) VALUES (1,28.5,'BLUE',20,40),(2,45,'GREY',20,30),(3,32.2,'GREEN',175,340.5),(4,59,'BROWN',133,258.8);
INSERT INTO SUPPART(SUPPLIER_CODE,PART_CODE,QUANTITY) VALUES ('S1004',2,4),('S1002',1,7),('S1001',4,5),('S1000',3,10);

SELECT SUPPLIER_CODE,PART_CODE FROM SUPPART ORDER BY SUPPLIER_CODE;
/*Get the details of supplier who operate from Bombay with turnover 50.*/
SELECT * FROM SUP WHERE SUPPLIER_CITY='BOMBAY' AND TURNOVER>50 ;
/*Get the total number of supplier.*/
SELECT COUNT(SUPPLIER_CODE) FROM SUP;
/*Get the part number weighing between 25 and 35.*/
SELECT PART_CODE FROM PA WHERE WEIGHT BETWEEN 25 AND 35;
/*Get the supplier number whose turnover is null.*/
SELECT SUPPLIER_CODE FROM SUP WHERE TURNOVER= NULL;
/*Get the part number that cost 20, 30 or 40 rupees.*/
SELECT PART_CODE FROM PA WHERE COST IN(20,30,40);
/*Get the total quantity of part 2 that is supplied*/
SELECT QUANTITY FROM SUPPART WHERE PART_CODE=2;
/* Get the part number whose cost is greater than the average cost*/
SELECT PART_CODE FROM PA WHERE COST>(SELECT AVG(COST) FROM PA);
/*Get the supplier number and turnover in descending order of turnover.*/
SELECT SUPPLIER_CODE,TURNOVER FROM SUP ORDER BY TURNOVER DESC;